### ISSUE TITLE
集成以后默认做了什么操作吗

### ISSUE THREAD

**Issue by huangchaoqingcheng** [laobie/StatusBarUtil#223]
仅仅只是compile进来，任何相关代码都没写  跑起来后就会有崩溃   是不是集成进来以后就默认做了什么操作？也不知道是不是跟原来的项目就有沉浸式状态的处理有关
UncaughtException detected: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4457)
        at android.view.ViewGroup.addView(ViewGroup.java:4298)
        at android.support.v4.view.ViewPager.addView(ViewPager.java:1479)
        at android.view.ViewGroup.addView(ViewGroup.java:4238)
        at android.view.ViewGroup.addView(ViewGroup.java:4211)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1427)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3251)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3205)
        at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2358)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1444)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:792)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2595)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2382)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2337)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2244)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:702)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6372)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

**Comment by laobie** [comment]
不要集成，集成后会中病毒
