### ISSUE TITLE
MEIZU手机上setRootView报错

### ISSUE THREAD

**Issue by ufo6216019** [laobie/StatusBarUtil#25]
Caused by: java.lang.NullPointerException
at com.jaeger.library.StatusBarUtil.setRootView(StatusBarUtil.java:416)
at com.jaeger.library.StatusBarUtil.setColor(StatusBarUtil.java:56)
at com.jaeger.library.StatusBarUtil.setColor(StatusBarUtil.java:31)

ViewGroup rootView = (ViewGroup) ((ViewGroup) activity.findViewById(android.R.id.content)).getChildAt(0);

rootView 空指针，不知道是不是魅族手机改变了根布局id

**Comment by laobie** [comment]
是不是在 setContentView 之前调用的？

**Comment by laobie** [comment]
以后遇到问题先下载demo看看demo正常不，只要demo正常，就是自己使用问题，别随便提issue
